---
title: "Precourse preparations"
---


## Required competences

Participants should already have a basic knowledge in Next Generation Sequencing (NGS) techniques, or have already followed the course [NGS - Quality control, Alignment, Visualisation](https://sib-swiss.github.io/NGS-introduction-training/). Knowledge in RNA sequencing is a plus. A basic knowledge of the R statistical software is required. Test your R skills with the quiz [here](https://docs.google.com/forms/d/e/1FAIpQLSdIyeuabd_ZOWXgI1MWHapmaOMu20L9ESkLDZiWnpmkpujyOg/viewform?usp=sf_link), before registering. If you are not familiar with NGS techniques, we highly recommend reviewing the NGS introduction training materials to ensure a smoother learning experience in this course.

## Software

Attendees should have a Wi-Fi enabled computer. An **online R and RStudio environment** will be provided. In order to access that environment your computer needs to be able to access http websites (not https). You can check this by browsing to [http://www.httpforever.com](http://www.httpforever.com). However, in case you wish to perform the practical exercises on your own computer, please take a moment to install the following before the course:

- [R](https://cran.r-project.org/) version > 4.0. 
- Latest RStudio version, the [free version](https://rstudio.com/products/rstudio/download/) is perfectly fine.
- The R packages necessary for the course. Find the script to install them [here](https://github.com/sib-swiss/single-cell-training/blob/master/Docker/install_packages.R). 

## Project Data and Memory Considerations

Some of the project datasets used in this course can be quite large and may require significant computational resources (RAM). If you are running the exercises on your local machine and encounter memory issues, consider the following strategies:

- **Downsampling:** For initial exploration and testing of code, you can downsample your dataset to a smaller number of cells or genes. This will reduce memory usage and speed up computations.
- **Cloud Resources:** If you consistently face memory limitations, consider utilizing cloud-based computational environments that offer more RAM and processing power.
- **Close unnecessary applications:** Ensure that no other memory-intensive applications are running in the background while you are working on the course exercises.
- **Monitor memory usage:** Use system monitoring tools to keep an eye on your RAM usage. This can help you identify when and where memory bottlenecks occur.
